# Generated by Django 2.2.6 on 2019-10-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('registered_on', models.DateField()),
                ('serial_id', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[(1, 'CNG'), (2, 'PETROL'), (3, 'DIESEL'), (4, 'HYDROGEN'), (5, 'LIQUID NITROGEN'), (6, 'BIODIESEL')], max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dated', models.DateField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DriverDetails')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.FuelType')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priced_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_name', models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, to='upload.FuelType')),
            ],
        ),
    ]
