# Generated by Django 2.2.6 on 2019-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
