# Generated by Django 3.0.8 on 2020-09-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
